### ISSUE TITLE
[1.X][2.X] Connection occasionally times out and does not recover → app becomes unable to load sites

### ISSUE THREAD

**Issue by mtigas** [OnionBrowser/OnionBrowser#2]
**Workaround**: Force quit app (tap home to quit app, double-tap home, hold down on app icon in tray, and "delete" app) and then restart app.

---

Hard to recreate issue when running app for more than a few minutes.

Seems to happen regardless of if app has gone into background or if network has gone up/down. (In fact, app does send `HUP` to Tor in those circumstances, causing Tor to reload & build new connections.)
#3 would help (and is related), but this is a more specific issue than that.

**Comment by msc-** [comment]
Still happens on iOS 9. It is the biggest problem I have with OB. The friendlier error just makes one want to scream: "if they know about this, why don't they fix it?"

**Comment by DavidMOliver** [comment]
I want to add this to milestone 2.1 for tracking throughout milestones 2.1 - 2.9

**Comment by tladesignz** [comment]
@DavidMOliver: As discussed frequently on telcos: We're completely dependent on Tor Project with this. May need some more personal sessions with the Tor folks. (Did somebody say travel budget? ^^) So to put this in a milestone doesn't make too much sense at least in terms of the GitHub issue tracker. Multiple milestones are not possible anyway, here.

The propsal is another story, though.

**Comment by DavidMOliver** [comment]
@tladesignz no question we need help.  We'll work this out in a way that is not "our development work" and make the dependency clear in the proposal

**Comment by mtigas** [comment]
Quick update on this: A lot of work has been done by the core tor folks to try to at least allow us to kill tor (separately from killing the app process) and start it back up later. See https://trac.torproject.org/projects/tor/ticket/25510 (this is basically the "in-process restart" stuff mentioned in sub-tickets linked from there).

Tor has been updated to something newer than 0.3.3.X, which means we get this API.

I've enabled some experimental changes that @tladesignz put in, and left them very rough. 13fe387cd50a3370aaa9ecb3926419c231615fbc It's _super rough_: the "Connecting..." dialog doesn't appear again when the app comes back to foreground so there's a good chance that the app will still have a silent network hang if something bad happens. There's also good chance that this is super unstable and crashes. But it's worth putting it out in the TestFlight builds, IMO.

**Comment by tladesignz** [comment]
Finally with release 2.2.0 there's going to be Tor 0.3.5.8 contained which will should fix this for good.

However, I'll leave this issue open and forward it to the next release 2.3.0 for collection of feedback.

Additionally, there's one small issue left, as we currently don't get progress/connection feedback on restarts from the Tor binary, which could lead to situations, when the background restart doesn't work as expected.

So, not completely resolved, but mostly.

**Comment by tladesignz** [comment]
I'll close this now, as we didn't hear any complaints lately. The restart of Tor seems to be quite stable now.
