### ISSUE TITLE
"New Identity" button clears history but visited links still get ":visited" CSS style

### ISSUE THREAD

**Issue by sintime** [OnionBrowser/OnionBrowser#20]
As the title says.

Browser history / cache / cookies get cleared, but visited links still receive a CSS highlight for ":visited" (purple by default). This could be subject to crafty attacks, but the original script-based attack of this leak does not appear work on iOS Safari — http://ha.ckers.org/weird/CSS-history-hack.html — visited links on this page get proper highlight but do not end up in the "visited" section as the JS attempts to do.

A [warning message](https://d2p12wh0p3fo1n.cloudfront.net/files/20120905/1.png) now shows up in the 1.2.6 version (should be available approx Sep. 12) when pressing the "New Identity" button.

More details in the following comments:
- https://github.com/mtigas/iOS-OnionBrowser/issues/20#issuecomment-8318323
- https://github.com/mtigas/iOS-OnionBrowser/issues/20#issuecomment-8318759

---

**Original report:**

Some links on some .onion sites seem to remain purple regardless of pressing "new identity"  or indeed the complete deletion and reinstallation of the OnionBrowser.

I'm taking this as meaning there is some history being maintained?

**Comment by tladesignz** [comment]
This issue is almost 5 years old. I'll close it.
