### ISSUE TITLE
Integrate Plugins/JS Applications to build new applications

### ISSUE THREAD

**Issue by fpietrosanti** [OnionBrowser/OnionBrowser#23]
Hi,

is it possible to integrate browser plug-in or JS Application (as main UI) within Onion Browser?

For example, it would be a really cool idea to use Onion Browser to package other applications that just need a web view and tor integrated.

For example it would be possible to integrate:
- CryptoCat www.crypto.cat
- GlobaLeaks www.globaleaks.org

that both need to run as local javascript application, communicate with the web anonymous and use the web browser as their main UI.

Onion Browser may so became a base SDK to build Mobile Anonymized applications, much like the current goal of APAF (but for Desktop applications) http://github.com/globaleaks/APAF

What do you think about that possible direction of Onion Browser?

**Comment by tladesignz** [comment]
Orbot seems to make this superfluous. With that you can just use any package-a-website-into-an-app toolkit.
