### ISSUE TITLE
Onion Browser tells the timezone of user through JavaScript, unlike Tor Browser

### ISSUE THREAD

**Issue by abrasivemurk** [OnionBrowser/OnionBrowser#243]
This is very bad for privacy. Can you fix it? Tor Browser sets the timezone the same value for every use while Onion Browser tells the exact timezone of users.

**Comment by tladesignz** [comment]
Sorry, unable to fix.
Tor Browser has its own rendering engine (ok, they use Firefox, but anyway), which they are fully able to control. This is not possible on iOS.

The design goal for Onion Browser is, to look as if you would be on your normal Safari browser.

See #227 and esp. this comment about some background: https://github.com/OnionBrowser/OnionBrowser/issues/227#issuecomment-574309005
