### ISSUE TITLE
Ok, so I dug a little deeper into that privacy-pass plugin. It relies heavily on being run as a browser plugin (e.g. runs continuously in the background, makes use of hooks only available to plugins) and we can't run it just like that in a UIWebView context.

### ISSUE THREAD

**Issue by zettysource** [OnionBrowser/OnionBrowser#275]
Ok, so I dug a little deeper into that privacy-pass plugin. It relies heavily on being run as a browser plugin (e.g. runs continuously in the background, makes use of hooks only available to plugins) and we can't run it just like that in a UIWebView context.
I would need to change it completely, to run injected inside a website, only.

I sent @alxdavids, the main committer on that project a mail to ask about his opinion before I waste more time on this.

I also just played around with desktop Tor Browser, and it seems to have the exact same problem: The hCaptcha is shown over and over again. Adding that plugin seems to help, though.
(Also, I have to admit, it isn't shown every time. There seems to be some credibility calculation on CloudFlare's side and Tor Browser might to be nearer to the threshold than Onion Browser. May have something to do with exit nodes, too.)

_Originally posted by @tladesignz in https://github.com/OnionBrowser/OnionBrowser/issues/256#issuecomment-648908428_

**Comment by tladesignz** [comment]
I reported you to Github for the behaviour you showed in the last 2 days. Good riddance!
