### ISSUE TITLE
WKWebView support

### ISSUE THREAD

**Issue by chrisballinger** [OnionBrowser/OnionBrowser#47]
There is a new API called [WKWebView](http://nshipster.com/wkwebkit/) that supports JIT and is now the same on iOS and OS X. It also supports user scripts via [WKUserScript](https://developer.apple.com/library/prerelease/mac/documentation/WebKit/Reference/WKUserScript_Ref/index.html) which could be helpful.

I am considering creating some sort of TORWebView subclass of WKWebView that transparently supports Tor via OnionKit. Would you be interested in collaborating?

There is also a new API on iOS 8 that allows [full VPN control](http://ramezanpour.net/post/2014/08/03/configure-and-manage-vpn-connections-programmatically-in-ios-8/) via the `NEVPNManager` class. If many applications depend on Tor, it could be better from a security perspective to ship a Tor VPN that is maintained separately. My only concern would be that users might not want all of their phone's traffic going over Tor, only a few select applications.

**Comment by n8fr8** [comment]
It seems we might be able to use network extensions integrated directly into an app itself as a library/service?

**Comment by tladesignz** [comment]
https://benjaminerhart.com/2018/03/state-of-the-onion-ios/

**Comment by vilimas** [comment]
Hi @tladesignz I wanted to ask what is the state of getting WKWebView working with the tor network? Checked all information that I can found about problems with WKWebView and Network Extension but didn't see any good news.
Maybe there is a way to render the .onion page on WKWebView even if the benefit of the tor network (security and privacy) are lost?

**Comment by tladesignz** [comment]
> Hi @tladesignz I wanted to ask what is the state of getting WKWebView working with the tor network? Checked all information that I can found about problems with WKWebView and Network Extension but didn't see any good news.

Me neither. We're still working on getting to run a stable Network Extension. 15 MB still too small to have Tor run together with tun2tor/tun2socks glue code, so working on a split solution. Not there yet.

> Maybe there is a way to render the .onion page on WKWebView even if the benefit of the tor network (security and privacy) are lost?

Impossible. You need a Tor client to reach these sites. .onion sites are hidden in the Tor network. You need to negotiate and reach a rendezvous server in the Tor network.

**Comment by tladesignz** [comment]
We're almost there:
https://github.com/iCepa/iCepa/commit/7ca88f77267f6131e8561be6dbb58b190f74551c

Still lacking:
- Can't resolve .onion addresses. Something in iOS is blocking this.
- Snowflake seems to no support outbound proxy: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/issues/40069

**Comment by tladesignz** [comment]
It is finally done! Onion Browser 3.0.0 is released, which relies on Orbot iOS to provide a Network Extension with Tor and could therefore finally switch to `WKWebView`!
