### ISSUE TITLE
Allow some manual torrc configuration (for things like HidServAuth)

### ISSUE THREAD

**Issue by bigzaqui** [OnionBrowser/OnionBrowser#74]
Hi!

following the tutorial for hass https://home-assistant.io/cookbook/tor_configuration/ I got the Onion browser but can't find the way to add my authentication cookie, is this a missing feature?

**Comment by mtigas** [comment]
Hi @bigzaqui: There isn't any way to manually edit the torrc, mainly because I was originally matching the way Tor Browser Bundle operates. I'm going to work on a way to allow *some* control over custom config lines for things like this in the future. (I use quite a few authenticated hidden services myself, just don't use them in Onion Browser at this point.)

**Comment by attzonko** [comment]
This would be great

**Comment by attzonko** [comment]
I also have my home assistant instance as a .onion hidden site and would love to be able to get to it from my iOS devices by somehow setting 'HidServAuth'.  Would be happy to do any beta testing for a feature like that.

**Comment by Andalore** [comment]
I am also using home assistant and would highly appreciate the feature for manual torrc configuration.

**Comment by ghost** [comment]
Same for me:
I'm using using Home Assistant, was able to get remote access via Tor on my windows PC, have also installed the Onion Browser on my iOS device, but can't find a way to find and change the torrc-default settings.
Would love to be able to use this feature on my iOS devices.
Any suggestions ?

**Comment by roqvist** [comment]
Any progress on this?

**Comment by ncarding** [comment]
I'm looking to do this too. Any news on it's development?

**Comment by n8fr8** [comment]
Live from the Tor dev meeting, just bringing this ticket back up, because iOS people are people too and want to do fancy torrc things!

**Comment by roqvist** [comment]
Onion Browser 2 seems well prepared for this, with a nice settings page available per page.

Really missing the HidServAuth, any roadmap on this?

**Comment by r3ckd** [comment]
UX discussion: user needs a facility for entering keyword/value pairs and then have those immediately sent to TOR.  Option to enter "raw text" or pairs and then [APPLY] button to set.  TOR will respond to those setting events, needs to be a UX for receiving that response.

**Comment by tladesignz** [comment]
Note to myself: Need to have a look at the Tor config code again, to define, how the format of additional config options needs to be, which will partly define the UI.
Will reply here.

**Comment by tladesignz** [comment]
I did a first stab at this, without UI drafts. This is really for very advanced users, because there's no failure mode feedback, but should do for people who are advanced enough to use `HidServAuth`.

**Comment by munsuri** [comment]
I believe the changes to support HidServAuth should have naturally allowed the use of ExitNodes as well but I can’t get Tor to connect when in use. I have checked the code related to AdvancedTorConf and I don’t see why it shouldn’t work. Am I missing something or it is not really supposed to work like in the torrc file? Thanks

**Comment by tladesignz** [comment]
So, I played around a little. For simplicity's sake I used the following:

```--ExcludeExitNodes``` 
```{fi}, {nl}, {us}```

I added one country after another, just what I got as exit nodes then.
Then restarted every time.

Looks very much like it works to me. Tor seemed to honor my choices.


Please note:

- Onion Browser does not make use of the `.torrc` file. Instead, everything is handed over as arguments.
- There's no command line preprocessing. There's no bash, splitting the full command into arguments. Argument splitting needs to be done by you! Therefore, don't put an argument option and it's values in one line. Use two!
- There's no other preprocessing done by Onion Browser. You need to follow what Tor wants, exactly! Add the two minus signs (--) before a command line option. Follow rules on capitalization and spacing! (Although, Tor mostly is ignoring capitalization, AFAIK)

**Comment by munsuri** [comment]
Aha, the manual (two line) argument splitting was it! It wasn’t initially obvious to me but now looking at the code again makes sense.
Thank you so much for such a quick reply and explanation of additional considerations, much appreciated.
